Models/MyCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace LOLEMCosmetics.Models
{
    public class MyCart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(LOLEM LOLEM, int quantity)
        {
            CartLine line = Lines
            .Where(b => b.LOLEM.LOLEMID == LOLEM.LOLEMID)
            .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    LOLEM = LOLEM,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(LOLEM LOLEM) =>
        Lines.RemoveAll(l => l.LOLEM.LOLEMID == LOLEM.LOLEMID);
        public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.LOLEM.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public LOLEM LOLEM { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using LOLEMCosmetics.Models;
using System.Linq;
namespace LOLEMCosmetics.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private MyCart cart;
        public OrderController(IOrderRepository repoService, MyCart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Xin lỗi, giỏ hàng của bạn trống!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/MyCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LOLEMCosmetics.MyTagHelper;
using LOLEMCosmetics.Models;
using System.Linq;
namespace LOLEMCosmetics.Pages
{
    public class MyCartModel : PageModel
    {
        private ILOLEMCosmeticsRepository repository;
        public MyCartModel(ILOLEMCosmeticsRepository repo, MyCart myCartService)
        {
            repository = repo;
            myCart = myCartService;
        }
        public MyCart myCart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long LOLEMId, string returnUrl)
        {
            LOLEM LOLEM = repository.LOLEMs
            .FirstOrDefault(b => b.LOLEMID == LOLEMId);
            myCart.AddItem(LOLEM,
                           1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long LOLEMId, string returnUrl)
        {
            myCart.RemoveLine(myCart.Lines.First(cl =>
            cl.LOLEM.LOLEMID == LOLEMId).LOLEM);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Completed.cshtml
@page
<div class="text-center">
    <h3>Cảm ơn bạn đã đặt hàng #@OrderId</h3>
    <p>Chúng tôi sẽ gửi hàng cho bạn trong thời gian sớm nhất.</p>
    <a class="btn btn-info" asp-controller="Home">Quay lại cửa hàng</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/MyCart.cshtml
@page
@model MyCartModel
<h2>Giỏ Hàng</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>Số Lượng</th>
            <th>Tên Sản Phẩm </th>
            <th class="text-right">Giá bán </th>
            <th class="text-right">Tổng Phụ</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.myCart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.LOLEM.Title</td>
                <td class="text-right">@line.LOLEM.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.LOLEM.Price).ToString("c"))
                </td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="LOLEMID"
                               value="@line.LOLEM.LOLEMID" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Xóa 
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Tổng Hóa Đơn:</td>
            <td class="text-right">
                @Model.myCart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn btn-info" href="@Model.ReturnUrl">Tiếp Tục Mua Sắm </a>
    <a class="btn btn-info" asp-action="Checkout" asp-controller="Order">
        Thanh Toán Ngay 
    </a>
</div>

Pages/_MyCartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LOLEM Cosmetics</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">LOLEM Cosmetics</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>